### ISSUE TITLE
Add Travis build; Update tests to latest LaTeXML

### ISSUE THREAD

**Issue by physikerwelt** [dginev/LaTeXML-Plugin-ltxpsgi#4]
see https://gist.github.com/physikerwelt/bc5373d4ad8d85ce6a1a

**Comment by dginev** [comment]
I updated the tests and added a Travis build, which is failing for mysterious reasons. Trying to get things fixed now.

**Comment by dginev** [comment]
Sigh, the math profile requires xcolor with dvipsnames enabled, which is defined in a .def file only available in texlive. I don't want to install texlive in Travis, hence the error. If anything I got motivated to include full dumps in the test failure reports, which will be helpful in the future.

**Comment by dginev** [comment]
Ok, the Travis build is passing and we have better test failure reports for future problems. 

Joy! Thanks for the report, we have revived the ltxpsgi plugin back to 0.8.1 compatibility.
