### ISSUE TITLE
consistent data format for "status_code"

### ISSUE THREAD

**Issue by physikerwelt** [dginev/LaTeXML-Plugin-ltxpsgi#5]
Before the next test
 ```
		p.remove( new BasicNameValuePair( "preload", "texvc" ) );
		t.setParams( p );
		assertEquals( withoutTexvc, t.request( "\\sen" ) );
		assertEquals( "2", t.getOb().get( "status_code" ) );
```
fails... the return code 0,3 are integers 2 is a string.

**Comment by dginev** [comment]
Perl doesn't differentiate between integers and strings :) But OK, let me see what I can do.

**Comment by dginev** [comment]
Just checked all places in the ltxpsgi and LaTeXML repositories that refer to the status code, they are returning integers everywhere. There is a chance the JSON serialization goes crazy for some weird reason, but nothing I can easily see. So closing for now, let me know if this bugs you again.
